### ISSUE TITLE
Idea: YouTube tutorials on Kusto?

### ISSUE THREAD

**Issue by jruales** [yonileibowitz/yonileibowitz.github.io#3]
Hey Yoni! Just wanted to suggest that maybe you should consider making YouTube videos with the content of the blog posts (in addition to the blog!). Videos have become quite popular for learning new things, and I think that there's a set of users that turn to YouTube when it comes to learning a new technologies (plus there's also the recommendation feed for people who have already watched other Kusto videos could be recommended to watch yours without even explicitly looking for them).

**Comment by yonileibowitz** [comment]
Hey @jruales, 

Thanks for the helpful feedback and idea!

I'll certainly consider it.
